'use client'

import { motion } from 'framer-motion'
import {
  Target,
  Shield,
  TrendingUp,
  Activity,
  MessageCircle,
  Wallet,
  MessageSquare,
  BarChart3,
  Users,
  Lightbulb,
  ExternalLink,
  AlertTriangle,
  ArrowLeft,
  Zap,
  ChevronRight,
} from 'lucide-react'
import FadeIn, { FadeInStagger } from '@/components/animations/FadeIn'
import { HoverScale } from '@/components/animations/ScaleIn'
import Link from 'next/link'
import { cn } from '@/lib/utils'
import { useEffect } from 'react'

const stats = [
  { value: '10,000+', label: 'Wallets Monitored', icon: Wallet, color: 'from-blue-500 to-cyan-500' },
  { value: '250,000+', label: 'Tweets Analyzed Daily', icon: MessageCircle, color: 'from-sky-500 to-blue-600' },
  { value: '1,200+', label: 'Signals Generated/Month', icon: TrendingUp, color: 'from-green-500 to-emerald-500' },
  { value: '500+', label: 'Elite Wallets Tracked', icon: Activity, color: 'from-purple-500 to-pink-500' },
  { value: '85%+', label: 'Signal Correlation Score', icon: BarChart3, color: 'from-orange-500 to-yellow-500' },
  { value: '10K+', label: 'Twitter Accounts Analyzed', icon: MessageSquare, color: 'from-violet-500 to-indigo-500' },
]

const values = [
  {
    icon: Shield,
    title: 'Transparency First',
    description: 'Every signal includes rationale. We show our work — the on-chain data, sentiment scores, and correlation metrics behind each recommendation.',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    icon: Target,
    title: 'Data-Driven Methodology',
    description: 'No hype, no FOMO. Every signal is generated by a proprietary multi-factor engine combining whale wallet activity, social sentiment analysis, and market structure confirmation.',
    color: 'from-green-500 to-emerald-500',
  },
  {
    icon: Users,
    title: 'Community-Backed',
    description: 'Built by traders, for traders. Our methodology evolves through community feedback and continuous backtesting against real market conditions.',
    color: 'from-purple-500 to-pink-500',
  },
  {
    icon: Lightbulb,
    title: 'Continuous Innovation',
    description: 'We are a small but dedicated team actively developing new signal types, expanding our wallet database, and refining our correlation algorithms.',
    color: 'from-orange-500 to-yellow-500',
  },
]

const methodologySteps = [
  {
    step: '1',
    title: 'Data Collection',
    description: 'Our system continuously monitors 500+ known whale wallets across Ethereum, BSC, and Solana. Simultaneously, we scrape and score 10,000+ crypto Twitter accounts for sentiment signals.',
  },
  {
    step: '2',
    title: 'Signal Processing',
    description: 'On-chain transactions are parsed for accumulation/distribution patterns. Twitter sentiment is scored using a proprietary NLP model that weights accounts by influence and historical accuracy.',
  },
  {
    step: '3',
    title: 'Correlation Engine',
    description: 'Our unique algorithm cross-references whale activity with social sentiment. When both align above 85%, a Diamond Signal is generated — our highest confidence alert.',
  },
  {
    step: '4',
    title: 'Validation & Delivery',
    description: 'Each signal passes through a multi-stage validation pipeline. Confirmed signals are pushed in real-time to Premium users and made available with 24hr delay on the Free tier.',
  },
]

export default function AboutPage() {
  useEffect(() => {
    // Set document title for 'use client' page
    document.title = 'About ChainPulse Alpha | AI-Powered Crypto Signal Platform'
    
    // Inject schema.org JSON-LD for the organization
    const scriptOrg = document.createElement('script')
    scriptOrg.type = 'application/ld+json'
    scriptOrg.id = 'schema-organization'
    scriptOrg.textContent = JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name: 'ChainPulse Alpha',
      url: 'https://chainpulsealpha.com',
      description: 'AI-powered crypto signal platform combining on-chain whale wallet tracking with Twitter sentiment analysis to generate actionable trading signals.',
      foundingDate: '2024',
      founders: [
        { '@type': 'Person', name: 'ChainPulse Team' }
      ],
      sameAs: [
        'https://twitter.com/chainpulsealpha'
      ],
      knowsAbout: [
        'Cryptocurrency Trading',
        'Blockchain Analytics',
        'Machine Learning',
        'Sentiment Analysis',
        'On-Chain Data',
      ],
      offers: {
        '@type': 'Service',
        name: 'Crypto Signal Services',
        description: 'AI-generated crypto trading signals from whale tracking and sentiment analysis',
        isRelatedTo: {
          '@type': 'Service',
          name: 'Diamond Signals',
          description: 'High-confidence signals with 85%+ correlation score threshold'
        }
      }
    })
    document.head.appendChild(scriptOrg)

    return () => {
      const el = document.getElementById('schema-organization')
      if (el) el.remove()
    }
  }, [])

  return (
    <main className="min-h-screen bg-background">
      {/* Schema-org Person data (hidden) */}
      <div style={{ display: 'none' }} itemScope itemType="https://schema.org/WebPage">
        <meta itemProp="name" content="About ChainPulse Alpha | AI-Powered Crypto Signal Platform" />
        <meta itemProp="description" content="Learn about ChainPulse Alpha's mission, methodology, and the team building AI-powered crypto signals with on-chain whale tracking and sentiment analysis." />
        <div itemProp="publisher" itemScope itemType="https://schema.org/Organization">
          <meta itemProp="name" content="ChainPulse Alpha" />
          <meta itemProp="url" content="https://chainpulsealpha.com" />
        </div>
      </div>

      <div className="container mx-auto px-4 py-16">
        {/* Back Link */}
        <FadeIn>
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-text-muted hover:text-primary-400 transition-colors mb-8"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
        </FadeIn>

        {/* Hero Section */}
        <FadeIn>
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary-500/20 text-primary-400 text-sm mb-6">
              <Zap className="w-4 h-4" />
              <span>About ChainPulse Alpha</span>
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6">
              Building the future of{' '}
              <span className="gradient-text">data-driven crypto signals</span>
            </h1>
            <p className="text-text-secondary max-w-3xl mx-auto text-lg leading-relaxed">
              ChainPulse Alpha is a next-generation crypto signal platform that combines 
              on-chain whale wallet intelligence with AI-powered social sentiment analysis. 
              Our mission is to democratize access to professional-grade trading insights 
              — giving retail traders the same quality of data that institutions use.
            </p>
          </div>
        </FadeIn>

        {/* Mission Statement */}
        <FadeIn delay={0.1}>
          <div className="glass-card p-8 md:p-12 rounded-2xl border border-primary-500/20 mb-16 text-center">
            <Target className="w-12 h-12 text-primary-400 mx-auto mb-4" />
            <h2 className="text-2xl md:text-3xl font-bold mb-4">Our Mission</h2>
            <p className="text-text-secondary max-w-3xl mx-auto leading-relaxed">
              Crypto markets move 24/7, driven by whales and sentiment shifts that most traders 
              can&apos;t track. We built ChainPulse Alpha to level the playing field. By monitoring 
              <strong className="text-text-primary"> 500+ elite wallets</strong> and analyzing{' '}
              <strong className="text-text-primary"> 250,000+ tweets daily</strong>, our system 
              identifies high-conviction trading opportunities before they hit the mainstream.
            </p>
          </div>
        </FadeIn>

        {/* Statistics Grid */}
        <FadeIn delay={0.15}>
          <div className="mb-16">
            <h2 className="text-2xl font-bold text-center mb-8">
              By the <span className="gradient-text">Numbers</span>
            </h2>
            <div className="grid grid-cols-1 xs:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
              {stats.map((stat) => (
                <HoverScale key={stat.label}>
                  <motion.div
                    className="glass-card p-6 text-center border border-border hover:border-primary-500/30 transition-all duration-300"
                    whileHover={{ y: -4 }}
                  >
                    <div className={`w-12 h-12 mx-auto mb-4 rounded-xl bg-gradient-to-br ${stat.color} p-0.5`}>
                      <div className="w-full h-full rounded-xl bg-background-card flex items-center justify-center">
                        <stat.icon className="w-6 h-6 text-white" />
                      </div>
                    </div>
                    <div className="text-3xl font-bold gradient-text mb-1">{stat.value}</div>
                    <div className="text-text-muted text-sm">{stat.label}</div>
                  </motion.div>
                </HoverScale>
              ))}
            </div>
          </div>
        </FadeIn>

        {/* Our Values */}
        <FadeIn delay={0.2}>
          <div className="mb-16">
            <h2 className="text-2xl font-bold text-center mb-8">
              What We <span className="gradient-text">Stand For</span>
            </h2>
            <div className="grid md:grid-cols-2 gap-6">
              {values.map((value) => (
                <HoverScale key={value.title}>
                  <motion.div
                    className="glass-card p-8 rounded-2xl border border-border hover:border-primary-500/30 transition-all duration-300 h-full"
                    whileHover={{ y: -4 }}
                  >
                    <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${value.color} p-0.5 mb-4`}>
                      <div className="w-full h-full rounded-xl bg-background-card flex items-center justify-center">
                        <value.icon className="w-6 h-6 text-white" />
                      </div>
                    </div>
                    <h3 className="text-lg font-semibold mb-2">{value.title}</h3>
                    <p className="text-text-secondary text-sm leading-relaxed">{value.description}</p>
                  </motion.div>
                </HoverScale>
              ))}
            </div>
          </div>
        </FadeIn>

        {/* Methodology */}
        <FadeIn delay={0.25}>
          <div className="mb-16">
            <h2 className="text-2xl font-bold text-center mb-4">
              Our <span className="gradient-text">Methodology</span>
            </h2>
            <p className="text-text-secondary text-center max-w-2xl mx-auto mb-10">
              Every signal is the product of a rigorous, multi-stage process that combines 
              on-chain data, social sentiment, and market structure analysis.
            </p>

            <div className="relative">
              {/* Connecting line */}
              <div className="hidden md:block absolute left-1/2 top-0 bottom-0 w-0.5 bg-gradient-to-b from-primary-500/40 via-secondary-500/40 to-accent-400/40 -translate-x-1/2" />

              <div className="space-y-8 md:space-y-12">
                {methodologySteps.map((step, index) => (
                  <motion.div
                    key={step.step}
                    initial={{ opacity: 0, x: index % 2 === 0 ? -30 : 30 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.5, delay: index * 0.1 }}
                    className={cn(
                      "flex flex-col md:flex-row items-start gap-6",
                      index % 2 === 0 ? "md:flex-row" : "md:flex-row-reverse"
                    )}
                  >
                    {/* Content */}
                    <div className="flex-1 glass-card p-6 rounded-xl border border-border">
                      <div className="flex items-center gap-3 mb-2">
                        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary-500 to-secondary-500 flex items-center justify-center text-white text-sm font-bold">
                          {step.step}
                        </div>
                        <h3 className="text-lg font-semibold">{step.title}</h3>
                      </div>
                      <p className="text-text-secondary text-sm leading-relaxed ml-11">
                        {step.description}
                      </p>
                    </div>

                    {/* Center dot */}
                    <div className="hidden md:flex flex-shrink-0 w-8 h-8 rounded-full bg-primary-500/20 border-2 border-primary-500 items-center justify-center relative z-10">
                      <div className="w-3 h-3 rounded-full bg-primary-500" />
                    </div>

                    {/* Spacer for odd side */}
                    <div className="hidden md:block flex-1" />
                  </motion.div>
                ))}
              </div>
            </div>
          </div>
        </FadeIn>

        {/* Team Section */}
        <FadeIn delay={0.3}>
          <div className="mb-16">
            <div className="text-center mb-10">
              <h2 className="text-2xl font-bold mb-3">
                The <span className="gradient-text">Team</span>
              </h2>
              <p className="text-text-secondary max-w-2xl mx-auto">
                ChainPulse Alpha is being built by a small, dedicated team of crypto enthusiasts, 
                data scientists, and software engineers. We are actively expanding our team 
                and capabilities — if our mission resonates with you,{' '}
                <Link href="/contact" className="text-primary-400 hover:text-primary-300 underline">
                  we would love to hear from you
                </Link>.
              </p>
            </div>

            <div className="glass-card p-8 rounded-2xl border border-border text-center max-w-2xl mx-auto">
              <div className="w-20 h-20 rounded-full bg-gradient-to-br from-primary-500 to-secondary-500 p-0.5 mx-auto mb-4">
                <div className="w-full h-full rounded-full bg-background-card flex items-center justify-center">
                  <Users className="w-8 h-8 text-white" />
                </div>
              </div>
              <h3 className="text-xl font-semibold mb-2">A Startup in Motion</h3>
              <p className="text-text-secondary text-sm leading-relaxed mb-4">
                We are a small but growing team building the future of crypto signal intelligence. 
                Our backgrounds span blockchain development, quantitative finance, machine learning, 
                and UI/UX design. We are committed to transparency, data quality, and continuous 
                improvement of our signal methodology.
              </p>
              <div className="flex flex-wrap justify-center gap-3">
                <Link
                  href="/contact"
                  className="inline-flex items-center gap-2 text-sm text-primary-400 hover:text-primary-300 transition-colors"
                >
                  <ExternalLink className="w-4 h-4" />
                  Connect with us
                </Link>
              </div>
            </div>
          </div>
        </FadeIn>

        {/* Risk Disclaimer */}
        <FadeIn delay={0.35}>
          <div className="glass-card p-8 rounded-2xl border border-warning-500/30 bg-gradient-to-r from-warning-500/5 via-warning-500/10 to-warning-500/5 mb-8">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-warning-500 to-orange-500 p-0.5 flex-shrink-0">
                <div className="w-full h-full rounded-xl bg-background-card flex items-center justify-center">
                  <AlertTriangle className="w-5 h-5 text-warning-400" />
                </div>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-warning-400 mb-2">Risk Disclaimer</h3>
                <div className="text-text-secondary text-sm space-y-2 leading-relaxed">
                  <p>
                    <strong className="text-text-primary">No signal is guaranteed.</strong> Cryptocurrency trading carries 
                    substantial risk of loss. ChainPulse Alpha signals are generated by an AI-powered analysis engine 
                    and are provided for informational and educational purposes only. They do not constitute financial 
                    advice, investment recommendations, or solicitation to trade.
                  </p>
                  <p>
                    Past performance of signals — including Diamond Signals with 85%+ correlation scores — does not 
                    guarantee future results. Market conditions change rapidly, and all trading carries risk. 
                    Never trade with money you cannot afford to lose.
                  </p>
                  <p>
                    The methodology described on this page (whale wallet tracking, Twitter sentiment analysis, 
                    correlation scoring) is provided transparently so users can make informed decisions. However, 
                    signal accuracy depends on data availability, API reliability, and market conditions that may 
                    change without notice.
                  </p>
                  <p>
                    <strong>Always conduct your own research (DYOR)</strong> before making any trading decisions. 
                    Consider consulting with a qualified financial advisor.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </FadeIn>

        {/* CTA */}
        <FadeIn delay={0.4}>
          <div className="text-center glass-card p-12 rounded-2xl border border-primary-500/30">
            <Zap className="w-12 h-12 text-primary-400 mx-auto mb-4" />
            <h2 className="text-2xl font-bold mb-3">Ready to trade with data?</h2>
            <p className="text-text-secondary mb-6 max-w-md mx-auto">
              Join early access traders using ChainPulse Alpha to stay ahead of the market.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/signup"
                className="button-primary px-8 py-3 rounded-xl font-semibold text-center"
              >
                Start Free Today
              </Link>
              <Link
                href="/features"
                className="button-secondary px-8 py-3 rounded-xl font-semibold text-center"
              >
                View Features
              </Link>
            </div>
          </div>
        </FadeIn>
      </div>
    </main>
  )
}
