import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Live Crypto Signals — ChainPulse Alpha | AI-Powered Whale & Sentiment Alerts',
  description: 'Browse live crypto signals generated by AI using real-time whale wallet data and Twitter sentiment analysis. Free preview with 3 signals; upgrade for full real-time access.',
  alternates: {
    canonical: 'https://chainpulsealpha.com/signals',
  },
  openGraph: {
    title: 'Live Crypto Signals — ChainPulse Alpha',
    description: 'AI-generated crypto signals from whale tracking and sentiment analysis. See Diamond, Whale, and Sentiment signals updated hourly.',
    url: 'https://chainpulsealpha.com/signals',
  },
}

export default function SignalsLayout({ children }: { children: React.ReactNode }) {
  return children
}
